"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "de" | "en" | "tr" | "fr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  de: {
    // Navigation
    "nav.whatIsTaskey": "Was ist Taskey?",
    "nav.features": "Features",
    "nav.liveDemo": "Live Demo",
    "nav.pricing": "Preise",
    "nav.about": "Über uns",
    "nav.support": "Support",
    "nav.bookDemo": "Demo buchen",
    "nav.tryFree": "Kostenlos testen",

    // Hero
    "hero.title": "Die Nr. 1 Dienstleistungssoftware für effiziente Betriebe",
    "hero.title.highlight": "Nr. 1",
    "hero.subtitle": "Zeitersparnis von durchschnittlich 25–30 Stunden pro Monat. Automatische Zeiterfassung, intelligente Auftragsplanung und digitale Rechnungsstellung für über 600 Branchen. Made in Germany, DSGVO-konform.",
    "hero.subtitle.highlight": "25-30h pro Monat",
    "hero.cta.demo": "Demo buchen",
    "hero.cta.trial": "14 Tage kostenlos testen",

    // FeaturePreview
    "features.badge": "Kernfunktionen",
    "features.title": "Die Grundpfeiler von Taskey",
    "features.title.em": "von",
    "features.subtitle": "Drei Säulen, die Ihren Betrieb effizienter, transparenter und profitabler machen.",
    "features.1.title": "Automatische Zeiterfassung",
    "features.1.desc": "Arbeitszeiten werden digital und ohne manuelle Eingaben erfasst. Weniger Papierkram, fehlerfreie Abrechnung und volle Transparenz für Ihr gesamtes Team.",
    "features.2.title": "Intuitive Auftragsplanung",
    "features.2.desc": "Projekte, Termine und Einsatzpläne zentral steuern. Routenoptimierung und automatische Terminvergabe sorgen dafür, dass Ihr Team immer zur richtigen Zeit am richtigen Ort ist.",
    "features.3.title": "Finanz- & Buchhaltungsübersicht",
    "features.3.desc": "Rechnungen direkt aus der App erstellen und versenden. Umsatz, Budget und Kosten in Echtzeit – inklusive automatischer Rentabilitätsanalyse für jedes Projekt.",

    // NFC Section
    "nfc.badge": "INNOVATION: NFC-TAGS",
    "nfc.title": "Kleben. Scannen. Wissen.",
    "nfc.subtitle": "Gib deinem Betrieb ein digitales Gedächtnis. Jede Maschine, jede Anlage wird smart.",
    "nfc.1.title": "Werkzeug & Maschinen-Tracking",
    "nfc.1.desc": "Nie wieder Werkzeug auf der Großbaustelle vergessen. Jeder Scan wird mit GPS-Standort protokolliert.",
    "nfc.2.title": "GPS-Tracking für Werkzeug",
    "nfc.2.desc": "Nie wieder Werkzeug auf der Großbaustelle vergessen. Der letzte Scan-Standort wird auf der Karte angezeigt.",
    "nfc.3.title": "Rechtssicherer Nachweis",
    "nfc.3.desc": "Scan-Zeitstempel belegen: Dein Team war vor Ort und hat geprüft. Perfekt für Versicherung & Haftungsfragen.",
    "nfc.4.title": "Wissens-Sicherung",
    "nfc.4.desc": "Dein bester Geselle geht in Rente? Das Wissen bleibt am Objekt — nicht in seinem Kopf.",
    "nfc.stat1": "Unbegrenzt wiederverwendbar",
    "nfc.stat2": "Lebensdauer",
    "nfc.stat3": "Wasserdicht & wetterfest",

    // iOS App Section
    "ios.badge": "Mobile App",
    "ios.title": "Taskey für",
    "ios.title.highlight": "iOS",
    "ios.subtitle": "Aufträge verwalten, Zeiten erfassen und Ihr Team koordinieren – alles direkt von Ihrem iPhone oder iPad.",
    "ios.feature1.label": "Intuitive Oberfläche",
    "ios.feature1.desc": "Klare Struktur, die sofort verständlich ist – ohne Schulung.",
    "ios.feature2.label": "Offline-fähig",
    "ios.feature2.desc": "Arbeiten Sie auch ohne Netz – Daten synchronisieren sich automatisch.",
    "ios.feature3.label": "Push-Benachrichtigungen",
    "ios.feature3.desc": "Echtzeit-Updates zu Aufträgen, Zeiten und Teamänderungen.",
    "ios.feature4.label": "Face ID & Touch ID",
    "ios.feature4.desc": "Sicherer Zugriff in Sekunden – ohne Passwort-Eingabe.",
    "ios.appstore": "Im App Store laden",
    "ios.allFeatures": "Alle Features entdecken",
    "ios.socialProof": "Genutzt von {count}+ Betrieben in Deutschland",

    // BusinessSize Section
    "biz.badge": "Für jeden Betrieb die richtige Lösung",
    "biz.title": "Taskey wächst",
    "biz.title.highlight": "mit Ihnen",
    "biz.card1.label": "1–5 Mitarbeiter",
    "biz.card1.text": "Sind Sie ein kleiner oder neu gegründeter Betrieb und möchten Arbeitszeiten, Abläufe und Arbeitstage effizienter organisieren?",
    "biz.card2.label": "6–20 Mitarbeiter",
    "biz.card2.text": "Wächst Ihr Betrieb und möchten Sie Teams, Projekte und Einsatzpläne zentral steuern – ohne den Überblick zu verlieren?",
    "biz.card3.label": "21–50 Mitarbeiter",
    "biz.card3.text": "Leiten Sie ein großes Unternehmen und benötigen Sie eine skalierbare Lösung für komplexe Strukturen, mehrere Teams und anspruchsvolle Einsatzplanung?",
    "biz.cta": "Zu den Angeboten →",

    // Testimonials
    "testimonials.title": "Dienstleister vertrauen auf Taskey",
    "testimonials.subtitle": "Über {count} zufriedene Betriebe in ganz Deutschland",
    "testimonials.1.text": "Mit Taskey haben wir unsere Verwaltungszeit um 70% reduziert. Mehr Zeit für unsere Kunden!",
    "testimonials.2.text": "Die automatische Zeiterfassung ist genial. Keine vergessenen Stunden mehr bei der Abrechnung.",
    "testimonials.3.text": "Endlich eine Software, die wirklich einfach zu bedienen ist. Mein Team war sofort produktiv.",

    // FAQ
    "faq.title": "Häufig gestellte Fragen",
    "faq.subtitle": "Alles, was Sie über Taskey wissen müssen",
    "faq.1.q": "Wie viel kostet Taskey?",
    "faq.1.a": "Taskey bietet flexible Preismodelle für jede Betriebsgröße. Schauen Sie sich unsere Preisseite für detaillierte Informationen an.",
    "faq.2.q": "Ist Taskey DSGVO-konform?",
    "faq.2.a": "Ja, Taskey ist vollständig DSGVO-konform. Ihre Daten werden auf deutschen Servern gespeichert und verschlüsselt übertragen.",
    "faq.3.q": "Brauche ich eine Schulung?",
    "faq.3.a": "Nein, Taskey ist so intuitiv gestaltet, dass Sie sofort loslegen können. Wir bieten aber optional kostenlose Onboarding-Sessions an.",
    "faq.4.q": "Funktioniert Taskey offline?",
    "faq.4.a": "Ja, die mobile App funktioniert auch offline. Alle Daten werden automatisch synchronisiert, sobald Sie wieder online sind.",
    "faq.5.q": "Kann ich bestehende Daten importieren?",
    "faq.5.a": "Ja, wir unterstützen den Import aus gängigen Formaten und helfen Ihnen beim Umzug von anderen Systemen.",
    "faq.6.q": "Wie schnell kann ich starten?",
    "faq.6.a": "Sie können sofort nach der Registrierung starten. Die Einrichtung dauert nur wenige Minuten.",
    "faq.7.q": "Gibt es eine Vertragsbindung?",
    "faq.7.a": "Nein, Sie können monatlich kündigen. Es gibt keine Mindestlaufzeit.",
    "faq.8.q": "Welchen Support bietet Taskey?",
    "faq.8.a": "Wir bieten deutschen E-Mail- und Telefon-Support während der Geschäftszeiten sowie eine umfangreiche Wissensdatenbank.",
    "faq.9.q": "Kann ich Taskey für mehrere Standorte nutzen?",
    "faq.9.a": "Ja, Taskey unterstützt Multi-Standort-Verwaltung mit zentraler Übersicht.",
    "faq.10.q": "Welche Geräte werden unterstützt?",
    "faq.10.a": "Taskey funktioniert auf allen modernen Geräten: iOS, Android, Windows, Mac und im Browser.",

    // Contact
    "contact.title": "Fragen zu Gebrauch oder Preispaketen?",
    "contact.subtitle": "Wir sind für Sie da – persönlich und kompetent",
    "contact.phone": "Telefon",
    "contact.email": "E-Mail",
    "contact.address": "Adresse",
    "contact.cta.title": "Überzeugt?",
    "contact.cta.subtitle": "Starten Sie jetzt kostenlos und sparen Sie durchschnittlich 25–30 Stunden pro Monat.",
    "contact.cta.highlight": "25-30h pro Monat",
    "contact.cta.demo": "Demo buchen",
    "contact.cta.trial": "14 Tage kostenlos testen",

    // Footer
    "footer.tagline": "Die Nr. 1 Dienstleistungssoftware aus Deutschland. Automatische Zeiterfassung, intelligente Auftragsplanung und digitale Rechnungsstellung für über 600 Branchen.",
    "footer.col.product": "Produkt",
    "footer.col.company": "Unternehmen",
    "footer.col.legal": "Rechtliches",
    "footer.col.contact": "Kontakt",
    "footer.link.features": "Features",
    "footer.link.pricing": "Preise",
    "footer.link.bookDemo": "Demo buchen",
    "footer.link.about": "Über uns",
    "footer.link.contact": "Kontakt",
    "footer.link.support": "Support",
    "footer.link.imprint": "Impressum",
    "footer.link.privacy": "Datenschutz",
    "footer.link.agb": "AGB",
    "footer.link.supportContact": "Support & Kontakt",
    "footer.rights": "Alle Rechte vorbehalten.",
    "footer.cookie": "Cookie-Einstellungen",
    "footer.madeIn": "🇩🇪 Made in Germany",

    // Branchen
    "branchen.title": "Für welche Branche möchten Sie Taskey nutzen?",
    "branchen.subtitle": "Taskey ist für über 600 Branchen geeignet – von Handwerk bis Facility Management.",
    "branchen.search": "Branche suchen...",
    "branchen.noResults": "Keine Branche gefunden",
    "branchen.cta": "Demo buchen",
    "branchen.ctaText": "Nicht gefunden? Kontaktieren Sie uns.",

    // About Page
    "about.hero.title": "Über Taskey",
    "about.hero.subtitle": "Die Software, die Dienstleistern wirklich hilft",
    "about.mission.p1": "Taskey wurde entwickelt, um Dienstleistungsbetrieben jeder Art den Alltag zu erleichtern. Wir haben gesehen, wie viel Zeit und Energie in manuelle Verwaltungsaufgaben fließt – Zeit, die besser in die eigentliche Arbeit und die Kunden investiert werden könnte. Ob Handwerk, Facility Management, technischer Service oder mobile Dienstleistungen – überall dort, wo Termine, Aufträge und Mitarbeiter koordiniert werden müssen, ist Taskey die Lösung.",
    "about.mission.p2": "Unsere Mission ist es, die beste und intuitivste Dienstleistungssoftware zu schaffen, die speziell auf die Bedürfnisse deutscher Betriebe zugeschnitten ist. Von der Elektroinstallation über Gebäudereinigung bis hin zu Event-Services – Taskey wächst mit Ihren Anforderungen. Made in Germany, DSGVO-konform und mit dem Service, den Sie erwarten dürfen.",
    "about.why.title": "Warum wir Taskey gebaut haben",
    "about.why.problem.title": "Das Problem",
    "about.why.problem.text": "Zu viele Dienstleister verlieren wertvolle Zeit mit manuellen Prozessen, unübersichtlichen Excel-Tabellen und komplizierten Softwarelösungen. Arbeitsstunden gehen verloren, Rechnungen werden zu spät gestellt, und die Übersicht fehlt.",
    "about.why.solution.title": "Unsere Lösung",
    "about.why.solution.text": "Mit Taskey haben wir eine All-in-One-Lösung geschaffen, die wirklich einfach zu bedienen ist. Automatische Zeiterfassung, intelligente Planung und digitale Abläufe sparen durchschnittlich 25-30h pro Monat – Zeit, die Ihnen für Ihr Geschäft bleibt.",
    "about.values.title": "Unsere Werte",
    "about.values.1.title": "Einfachheit",
    "about.values.1.text": "Software sollte den Alltag vereinfachen, nicht komplizierter machen. Deshalb ist Taskey intuitiv und ohne Schulung nutzbar.",
    "about.values.2.title": "Sicherheit",
    "about.values.2.text": "Ihre Daten sind bei uns sicher. DSGVO-konform, verschlüsselt und auf deutschen Servern gehostet.",
    "about.values.3.title": "Kundenservice",
    "about.values.3.text": "Wir sind für Sie da. Mit deutschem Support, schnellen Antworten und echten Menschen am anderen Ende der Leitung.",
    "about.team.title": "Unser Team",
    "about.team.founders": "Gründer",
    "about.team.team": "Team",
    "about.contact.title": "Kontakt & Impressum",
    "about.contact.phone": "Telefon",
    "about.contact.email": "E-Mail",
    "about.contact.address": "Adresse",
    "about.contact.more": "Weitere Informationen finden Sie in unserem",
    "about.contact.imprint": "Impressum",
    "about.contact.and": "und unserer",
    "about.contact.privacy": "Datenschutzerklärung",

    // Demo Page
    "demo.badge": "Live Demo verfügbar",
    "demo.hero.title": "Erleben Sie Taskey",
    "demo.hero.title.highlight": "live in Aktion",
    "demo.hero.subtitle": "Entdecken Sie, wie Taskey Ihren Betrieb revolutionieren kann —",
    "demo.hero.subtitle.strong": "ohne Anmeldung, ohne Verpflichtung.",
    "demo.cta": "Demo jetzt erleben",
    "demo.trust": "✓ Keine Kreditkarte erforderlich · ✓ Sofortiger Zugang · ✓ Realistische Daten",
    "demo.screenshots.label": "Einblicke",
    "demo.screenshots.title": "So sieht Taskey",
    "demo.screenshots.title.highlight": "in der Praxis",
    "demo.screenshots.title.suffix": "aus",
    "demo.benefits.label": "Warum die Demo testen?",
    "demo.benefits.title": "Überzeugen Sie sich",
    "demo.benefits.title.highlight": "selbst",
    "demo.benefit1.title": "Kompletter Überblick",
    "demo.benefit1.desc": "Sehen Sie alle Funktionen in Aktion — Dashboard, Aufträge, Zeiterfassung.",
    "demo.benefit2.title": "Keine Registrierung",
    "demo.benefit2.desc": "Sofortiger Zugang ohne Account — einfach klicken und loslegen.",
    "demo.benefit3.title": "Echte Daten",
    "demo.benefit3.desc": "Realistische Beispiel-Szenarien direkt aus dem Handwerk.",
    "demo.benefit4.title": "100% Kostenlos",
    "demo.benefit4.desc": "Keine versteckten Kosten, keine Kreditkarte erforderlich.",
    "demo.features.label": "Features",
    "demo.features.title": "Was Sie in der Demo",
    "demo.features.title.highlight": "entdecken",
    "demo.feature1": "Vollständiges Dashboard mit Echtzeitdaten",
    "demo.feature2": "Auftrags- und Projektverwaltung in Aktion",
    "demo.feature3": "Automatische Zeiterfassung und Mitarbeiterverwaltung",
    "demo.feature4": "GPS-Tracking und interaktive Kartenfunktion",
    "demo.feature5": "Berichte, Analysen und Auswertungen",
    "demo.feature6": "Kundenverwaltung und Kommunikation",
    "demo.cta2": "Jetzt kostenlos testen",
    "demo.bottom.text": "Die Demo läuft mit",
    "demo.bottom.strong": "realistischen Beispieldaten",
    "demo.bottom.text2": ", damit Sie genau sehen, wie Taskey in Ihrem Betrieb funktionieren würde.",
    "demo.links.what": "Was ist Taskey?",
    "demo.links.features": "Alle Funktionen",
    "demo.links.pricing": "Preise",

    // Pricing Page
    "pricing.hero.badge": "TRANSPARENT. FAIR. FLEXIBEL.",
    "pricing.hero.title": "Preise, die zu Ihrem Betrieb passen",
    "pricing.hero.subtitle": "Kein Versteckspiel. Alle Funktionen inklusive. Täglich kündbar.",
    "pricing.hero.cta.trial": "14 Tage kostenlos testen",
    "pricing.hero.cta.demo": "Demo buchen",
    "pricing.cancellation.label": "Kündigungsfrist für START:",
    "pricing.cancellation.monthly": "Täglich",
    "pricing.cancellation.quarterly": "Quartal (–7%)",
    "pricing.cancellation.yearly": "Jährlich (–13%)",
    "pricing.card.start.name": "START",
    "pricing.card.start.tagline": "Für kleine Betriebe",
    "pricing.card.start.desc": "Der einfache Einstieg für kleine Betriebe & Einzelunternehmer.",
    "pricing.card.grow.name": "GROW",
    "pricing.card.grow.tagline": "Am beliebtesten",
    "pricing.card.grow.desc": "Für wachsende Teams – mehr Kontrolle, mehr Effizienz.",
    "pricing.card.scale.name": "SCALE",
    "pricing.card.scale.tagline": "Für anspruchsvolle Betriebe",
    "pricing.card.scale.desc": "Für große Betriebe mit komplexen Anforderungen.",
    "pricing.card.perUser": "/ Nutzer / Monat",
    "pricing.card.cta.trial": "Kostenlos starten",
    "pricing.card.cta.demo": "Demo buchen",
    "pricing.card.cancellation": "Kündigung:",
    "pricing.card.cancellation.daily": "täglich",
    "pricing.card.cancellation.quarterly": "quartalsweise",
    "pricing.card.cancellation.yearly": "jährlich",
    "pricing.allfeatures.title": "Alles inklusive – bei jedem Paket",
    "pricing.allfeatures.subtitle": "Kein Feature-Locking. Keine versteckten Kosten. Alle Kernfunktionen sind in jedem Paket enthalten.",
    "pricing.allfeatures.datev.note": "DATEV / Lexware-Integration als optionales Add-on zubuchbar",
    "pricing.enterprise.badge": "FÜR GROSSBETRIEBE",
    "pricing.enterprise.title": "ENTERPRISE",
    "pricing.enterprise.subtitle": "Ab 50 Mitarbeiter",
    "pricing.enterprise.desc": "Maßgeschneiderte Lösungen für führende Organisationen. Dedizierter Support, SLA-Garantien und individuelle Integrationen.",
    "pricing.enterprise.cta1": "Mehr erfahren",
    "pricing.enterprise.cta2": "Enterprise anfragen",
    "pricing.nfc.badge": "ADD-ON",
    "pricing.nfc.title": "TASKEY NFC-TAGS",
    "pricing.nfc.subtitle": "Physische NFC-Tags für Ihre Maschinen, Werkzeuge und Anlagen",
    "pricing.nfc.starter.name": "Starter",
    "pricing.nfc.starter.tags": "10 NFC-Tags",
    "pricing.nfc.pro.name": "Pro",
    "pricing.nfc.pro.tags": "50 NFC-Tags",
    "pricing.nfc.business.name": "Business",
    "pricing.nfc.business.tags": "150 NFC-Tags",
    "pricing.nfc.month": "/ Monat",
    "pricing.nfc.order": "Jetzt bestellen",
    "pricing.nfc.info.title": "Kostenloser Ersatz",
    "pricing.nfc.info.text": "Beschädigte oder verlorene Tags werden kostenlos ersetzt. Einmalig, pro Jahr.",
    "pricing.onboarding.badge": "SETUP-SERVICE",
    "pricing.onboarding.title": "Schlüsselfertig. Done for You.",
    "pricing.onboarding.subtitle": "Wir richten Taskey komplett für Sie ein – damit Sie sofort starten können.",
    "pricing.onboarding.grow.name": "GROW Onboarding",
    "pricing.onboarding.grow.price": "990 €",
    "pricing.onboarding.grow.desc": "Komplett-Setup für GROW-Nutzer",
    "pricing.onboarding.scale.name": "SCALE Onboarding",
    "pricing.onboarding.scale.price": "2.490 €",
    "pricing.onboarding.scale.desc": "Enterprise-Setup für SCALE-Nutzer",
    "pricing.onboarding.cta": "Onboarding anfragen",
    "pricing.datev.badge": "ADD-ON",
    "pricing.datev.title": "DATEV / Lexware Integration",
    "pricing.datev.price": "11,89 € / Monat",
    "pricing.datev.forAll": "Zu jedem Paket zubuchbar",
    "pricing.datev.cta": "Jetzt zukaufen",
    "pricing.manager.badge": "PREMIUM SERVICE",
    "pricing.manager.title": "Taskey Premium Manager",
    "pricing.manager.subtitle": "Ihr persönlicher Experte für Ihren Betrieb",
    "pricing.manager.price": "239 € / Woche",
    "pricing.manager.cta1": "Mehr erfahren",
    "pricing.manager.cta2": "Jetzt anfragen",
    "pricing.storage.title": "Brauchen Sie mehr Speicher?",
    "pricing.storage.subtitle": "Erweitern Sie Ihren Speicherplatz flexibel nach Bedarf.",
    "pricing.storage.tier1": "+100 GB",
    "pricing.storage.tier2": "+500 GB",
    "pricing.storage.tier3": "+1 TB",
    "pricing.storage.month": "/ Monat",
    "pricing.storage.cta": "Jetzt zukaufen",
    "pricing.faq.title": "Häufige Fragen zu den Preisen",
    "pricing.faq.1.q": "Gibt es eine kostenlose Testphase?",
    "pricing.faq.1.a": "Ja! Sie können Taskey 14 Tage lang kostenlos testen – ohne Kreditkarte.",
    "pricing.faq.2.q": "Kann ich das Paket wechseln?",
    "pricing.faq.2.a": "Ja, Sie können jederzeit upgraden oder downgraden.",
    "pricing.faq.3.q": "Was passiert nach der Testphase?",
    "pricing.faq.3.a": "Nach 14 Tagen wählen Sie ein Paket oder das Konto wird pausiert – keine automatische Abbuchung.",
    "pricing.faq.4.q": "Sind Updates inklusive?",
    "pricing.faq.4.a": "Ja, alle Updates sind kostenlos und werden automatisch eingespielt.",
    "pricing.cta.title": "Bereit loszulegen?",
    "pricing.cta.subtitle": "Starten Sie jetzt kostenlos und sparen Sie durchschnittlich 25–30 Stunden pro Monat.",
    "pricing.cta.trial": "14 Tage kostenlos starten",
    "pricing.cta.demo": "Demo buchen",

    // Rollen Page
    "rollen.hero.title": "Rollen & Berechtigungen",
    "rollen.hero.subtitle": "Jede Rolle in Taskey ist auf ihre Aufgaben zugeschnitten – vom Außendienst bis zur Geschäftsführung",
    "rollen.overview.title": "Ein Überblick",
    "rollen.role.employee": "Mitarbeiter",
    "rollen.role.employee.desc": "Arbeiten beim Kunden und dokumentieren den Einsatz",
    "rollen.role.specialist": "Fachkraft",
    "rollen.role.specialist.desc": "Planen, kontrollieren und steuern aus dem Büro",
    "rollen.role.leader": "Leader",
    "rollen.role.leader.desc": "Führen das Unternehmen und haben volle Kontrolle",
    "rollen.cta.title": "Die richtige Rolle für jeden",
    "rollen.cta.subtitle": "Starten Sie jetzt und geben Sie jedem in Ihrem Team genau die Berechtigungen, die er braucht.",
    "rollen.cta.btn": "Kostenlos starten",

    // Was ist Taskey Page
    "was.hero.title.prefix": "Was ist",
    "was.hero.title.main": "Taskey",
    "was.hero.subtitle": "Mehr als Software – ein System zur Objektivierung von Arbeit",
    "was.principle.badge": "Grundprinzip",
    "was.principle.title": "Das Grundprinzip",
    "was.principle.not": "Taskey ist keine Zeiterfassung, kein Überwachungstool und keine Verwaltungssoftware.",
    "was.principle.is": "Taskey ist ein System zur Objektivierung von Arbeit",
    "was.principle.measurable": "Arbeit wird messbar, erklärbar und belegbar – ohne dass Menschen sich ständig rechtfertigen müssen.",
    "was.principle.facts": "Nicht Gefühle, Vermutungen oder Machtverhältnisse entscheiden, sondern nachvollziehbare Fakten.",
    "was.principle.trust": "Taskey ersetzt kein Vertrauen",
    "was.cta.title": "Bereit, Ihren Betrieb zu transformieren?",
    "was.cta.subtitle": "Starten Sie jetzt kostenlos und entdecken Sie, was Taskey für Sie tun kann.",
    "was.cta.trial": "14 Tage kostenlos testen",
    "was.cta.demo": "Demo buchen",

    // Enterprise Page
    "enterprise.hero.title.prefix": "Taskey",
    "enterprise.hero.title.highlight": "Enterprise",
    "enterprise.hero.subtitle": "Maßgeschneiderte, exklusive Lösungen für führende Organisationen — verfügbar nur für ausgewählte Partner",
    "enterprise.hero.admission": "Aufnahme nur auf Anfrage & Prüfung",
    "enterprise.hero.desc1": "Wir bieten ein streng limitiertes Enterprise‑Programm an. Bewerbungen werden individuell geprüft und nur Unternehmen akzeptiert, die unsere hohen Anforderungen an Größe, Sicherheitsstandards und geschäftliche Relevanz erfüllen.",
    "enterprise.hero.desc2": "Voraussetzungen können beispielsweise sein: Mindestgröße (100+ Angestellte), nachweisbare Marktführerschaft oder strategische Bedeutung sowie erweiterte Integrationsanforderungen.",
    "enterprise.hero.note": "Hinweis: Die Aufnahme erfolgt nach individueller Prüfung.",
    "enterprise.when.title": "Wann ist Enterprise das Richtige für Sie?",
    "enterprise.when.subtitle": "Wir empfehlen Enterprise für Unternehmen mit einzigartigen Anforderungen und strategischer Relevanz",
    "enterprise.cta.apply": "Enterprise anfragen",
    "enterprise.cta.demo": "Demo buchen",

    // Premium Manager Page
    "manager.hero.badge": "PREMIUM SERVICE",
    "manager.hero.title": "Taskey Premium Manager",
    "manager.hero.subtitle": "Ihr persönlicher Experte für Ihren Betrieb",
    "manager.cta.request": "Jetzt anfragen",
    "manager.cta.demo": "Demo buchen",
    "manager.price": "239 € / Woche",
  },

  en: {
    // Navigation
    "nav.whatIsTaskey": "What is Taskey?",
    "nav.features": "Features",
    "nav.liveDemo": "Live Demo",
    "nav.pricing": "Pricing",
    "nav.about": "About us",
    "nav.support": "Support",
    "nav.bookDemo": "Book a demo",
    "nav.tryFree": "Try for free",

    // Hero
    "hero.title": "The No. 1 service management software for efficient businesses",
    "hero.title.highlight": "No. 1",
    "hero.subtitle": "Save an average of 25–30 hours per month. Automatic time tracking, smart job scheduling and digital invoicing for over 600 industries. Made in Germany, GDPR-compliant.",
    "hero.subtitle.highlight": "25–30 hrs per month",
    "hero.cta.demo": "Book a demo",
    "hero.cta.trial": "Try free for 14 days",

    // FeaturePreview
    "features.badge": "Core Features",
    "features.title": "The pillars of Taskey",
    "features.title.em": "of",
    "features.subtitle": "Three pillars that make your business more efficient, transparent and profitable.",
    "features.1.title": "Automatic Time Tracking",
    "features.1.desc": "Working hours are recorded digitally without manual input. Less paperwork, error-free billing and full transparency for your entire team.",
    "features.2.title": "Intuitive Job Scheduling",
    "features.2.desc": "Manage projects, appointments and deployment plans centrally. Route optimisation and automatic scheduling ensure your team is always in the right place at the right time.",
    "features.3.title": "Finance & Accounting Overview",
    "features.3.desc": "Create and send invoices directly from the app. Revenue, budget and costs in real time – including automatic profitability analysis for every project.",

    // NFC Section
    "nfc.badge": "INNOVATION: NFC TAGS",
    "nfc.title": "Attach. Scan. Know.",
    "nfc.subtitle": "Give your business a digital memory. Every machine, every asset becomes smart.",
    "nfc.1.title": "Tool & Machine Tracking",
    "nfc.1.desc": "Never lose track of tools on a large construction site again. Every scan is recorded with a GPS location.",
    "nfc.2.title": "GPS Tracking for Equipment",
    "nfc.2.desc": "Never lose tools on a job site again. The last scan location is displayed on the map.",
    "nfc.3.title": "Legally Compliant Proof",
    "nfc.3.desc": "Scan timestamps prove your team was on site and carried out checks. Perfect for insurance and liability purposes.",
    "nfc.4.title": "Knowledge Retention",
    "nfc.4.desc": "Your best technician retiring? The knowledge stays with the asset — not in their head.",
    "nfc.stat1": "Unlimited reuse",
    "nfc.stat2": "Service life",
    "nfc.stat3": "Waterproof & weatherproof",

    // iOS App Section
    "ios.badge": "Mobile App",
    "ios.title": "Taskey for",
    "ios.title.highlight": "iOS",
    "ios.subtitle": "Manage jobs, track time and coordinate your team – all directly from your iPhone or iPad.",
    "ios.feature1.label": "Intuitive Interface",
    "ios.feature1.desc": "A clear structure that's immediately understandable – no training required.",
    "ios.feature2.label": "Works Offline",
    "ios.feature2.desc": "Work without internet – data syncs automatically once you're back online.",
    "ios.feature3.label": "Push Notifications",
    "ios.feature3.desc": "Real-time updates on jobs, hours and team changes.",
    "ios.feature4.label": "Face ID & Touch ID",
    "ios.feature4.desc": "Secure access in seconds – no password required.",
    "ios.appstore": "Download on the App Store",
    "ios.allFeatures": "Explore all features",
    "ios.socialProof": "Used by {count}+ businesses across Germany",

    // BusinessSize Section
    "biz.badge": "The right solution for every business",
    "biz.title": "Taskey grows",
    "biz.title.highlight": "with you",
    "biz.card1.label": "1–5 employees",
    "biz.card1.text": "Running a small or newly founded business and looking to organise working hours, workflows and daily operations more efficiently?",
    "biz.card2.label": "6–20 employees",
    "biz.card2.text": "Is your business growing and you want to manage teams, projects and schedules centrally – without losing the overview?",
    "biz.card3.label": "21–50 employees",
    "biz.card3.text": "Managing a larger company and need a scalable solution for complex structures, multiple teams and demanding deployment planning?",
    "biz.cta": "View plans →",

    // Testimonials
    "testimonials.title": "Service providers trust Taskey",
    "testimonials.subtitle": "Over {count} satisfied businesses across Germany",
    "testimonials.1.text": "With Taskey we reduced our admin time by 70%. More time for our customers!",
    "testimonials.2.text": "The automatic time tracking is brilliant. No more forgotten hours when it's time to invoice.",
    "testimonials.3.text": "Finally software that's genuinely easy to use. My team was productive straight away.",

    // FAQ
    "faq.title": "Frequently Asked Questions",
    "faq.subtitle": "Everything you need to know about Taskey",
    "faq.1.q": "How much does Taskey cost?",
    "faq.1.a": "Taskey offers flexible pricing plans for every business size. Check out our pricing page for detailed information.",
    "faq.2.q": "Is Taskey GDPR-compliant?",
    "faq.2.a": "Yes, Taskey is fully GDPR-compliant. Your data is stored on German servers and transmitted in encrypted form.",
    "faq.3.q": "Do I need any training?",
    "faq.3.a": "No, Taskey is so intuitive that you can get started immediately. We do offer optional free onboarding sessions.",
    "faq.4.q": "Does Taskey work offline?",
    "faq.4.a": "Yes, the mobile app works offline too. All data is synced automatically once you're back online.",
    "faq.5.q": "Can I import existing data?",
    "faq.5.a": "Yes, we support imports from common formats and will help you migrate from other systems.",
    "faq.6.q": "How quickly can I get started?",
    "faq.6.a": "You can start immediately after signing up. Setup takes just a few minutes.",
    "faq.7.q": "Is there a minimum contract term?",
    "faq.7.a": "No, you can cancel on a monthly basis. There is no minimum term.",
    "faq.8.q": "What support does Taskey offer?",
    "faq.8.a": "We offer German-language email and phone support during business hours, as well as a comprehensive knowledge base.",
    "faq.9.q": "Can I use Taskey across multiple locations?",
    "faq.9.a": "Yes, Taskey supports multi-location management with a centralised overview.",
    "faq.10.q": "Which devices are supported?",
    "faq.10.a": "Taskey works on all modern devices: iOS, Android, Windows, Mac and in the browser.",

    // Contact
    "contact.title": "Questions about usage or pricing plans?",
    "contact.subtitle": "We're here for you – personally and professionally",
    "contact.phone": "Phone",
    "contact.email": "E-Mail",
    "contact.address": "Address",
    "contact.cta.title": "Convinced?",
    "contact.cta.subtitle": "Start for free now and save an average of 25–30 hours per month.",
    "contact.cta.highlight": "25–30 hrs per month",
    "contact.cta.demo": "Book a demo",
    "contact.cta.trial": "Try free for 14 days",

    // Footer
    "footer.tagline": "The No. 1 service management software from Germany. Automatic time tracking, smart job scheduling and digital invoicing for over 600 industries.",
    "footer.col.product": "Product",
    "footer.col.company": "Company",
    "footer.col.legal": "Legal",
    "footer.col.contact": "Contact",
    "footer.link.features": "Features",
    "footer.link.pricing": "Pricing",
    "footer.link.bookDemo": "Book a demo",
    "footer.link.about": "About us",
    "footer.link.contact": "Contact",
    "footer.link.support": "Support",
    "footer.link.imprint": "Imprint",
    "footer.link.privacy": "Privacy Policy",
    "footer.link.agb": "Terms",
    "footer.link.supportContact": "Support & Contact",
    "footer.rights": "All rights reserved.",
    "footer.cookie": "Cookie settings",
    "footer.madeIn": "🇩🇪 Made in Germany",

    // Branchen
    "branchen.title": "Which industry would you like to use Taskey for?",
    "branchen.subtitle": "Taskey is suitable for over 600 industries – from trades to facility management.",
    "branchen.search": "Search industry...",
    "branchen.noResults": "No industry found",
    "branchen.cta": "Book a demo",
    "branchen.ctaText": "Not found? Contact us.",

    // About Page
    "about.hero.title": "About Taskey",
    "about.hero.subtitle": "The software that truly helps service businesses",
    "about.mission.p1": "Taskey was built to make daily operations easier for service businesses of all kinds. We saw how much time and energy goes into manual admin tasks – time that could be better invested in the actual work and the customers. Whether trades, facility management, technical services or mobile services – wherever appointments, jobs and staff need to be coordinated, Taskey is the solution.",
    "about.mission.p2": "Our mission is to build the best and most intuitive service software, specifically tailored to the needs of German businesses. From electrical installation to building cleaning to event services – Taskey grows with your requirements. Made in Germany, GDPR-compliant and with the service you deserve.",
    "about.why.title": "Why we built Taskey",
    "about.why.problem.title": "The Problem",
    "about.why.problem.text": "Too many service providers lose valuable time with manual processes, messy spreadsheets and complicated software. Working hours get lost, invoices go out late and the overview is missing.",
    "about.why.solution.title": "Our Solution",
    "about.why.solution.text": "With Taskey we've built an all-in-one solution that's genuinely easy to use. Automatic time tracking, smart scheduling and digital workflows save an average of 25–30 hours per month – time you get back for your business.",
    "about.values.title": "Our values",
    "about.values.1.title": "Simplicity",
    "about.values.1.text": "Software should simplify everyday life, not complicate it. That's why Taskey is intuitive and usable without training.",
    "about.values.2.title": "Security",
    "about.values.2.text": "Your data is safe with us. GDPR-compliant, encrypted and hosted on German servers.",
    "about.values.3.title": "Customer service",
    "about.values.3.text": "We're here for you. With German-speaking support, fast responses and real people at the other end of the line.",
    "about.team.title": "Our team",
    "about.team.founders": "Founders",
    "about.team.team": "Team",
    "about.contact.title": "Contact & Legal",
    "about.contact.phone": "Phone",
    "about.contact.email": "E-Mail",
    "about.contact.address": "Address",
    "about.contact.more": "Further information can be found in our",
    "about.contact.imprint": "Imprint",
    "about.contact.and": "and our",
    "about.contact.privacy": "Privacy Policy",

    // Demo Page
    "demo.badge": "Live demo available",
    "demo.hero.title": "Experience Taskey",
    "demo.hero.title.highlight": "live in action",
    "demo.hero.subtitle": "Discover how Taskey can revolutionise your business —",
    "demo.hero.subtitle.strong": "no sign-up, no commitment.",
    "demo.cta": "Try the demo now",
    "demo.trust": "✓ No credit card required · ✓ Instant access · ✓ Realistic data",
    "demo.screenshots.label": "Preview",
    "demo.screenshots.title": "This is what Taskey looks like",
    "demo.screenshots.title.highlight": "in practice",
    "demo.screenshots.title.suffix": "",
    "demo.benefits.label": "Why try the demo?",
    "demo.benefits.title": "See for yourself",
    "demo.benefits.title.highlight": "",
    "demo.benefit1.title": "Complete overview",
    "demo.benefit1.desc": "See all features in action — dashboard, jobs, time tracking.",
    "demo.benefit2.title": "No registration",
    "demo.benefit2.desc": "Instant access without an account — just click and go.",
    "demo.benefit3.title": "Real data",
    "demo.benefit3.desc": "Realistic example scenarios straight from the trades.",
    "demo.benefit4.title": "100% free",
    "demo.benefit4.desc": "No hidden costs, no credit card required.",
    "demo.features.label": "Features",
    "demo.features.title": "What you'll discover",
    "demo.features.title.highlight": "in the demo",
    "demo.feature1": "Complete dashboard with real-time data",
    "demo.feature2": "Job and project management in action",
    "demo.feature3": "Automatic time tracking and staff management",
    "demo.feature4": "GPS tracking and interactive map feature",
    "demo.feature5": "Reports, analytics and evaluations",
    "demo.feature6": "Customer management and communication",
    "demo.cta2": "Try for free now",
    "demo.bottom.text": "The demo runs with",
    "demo.bottom.strong": "realistic sample data",
    "demo.bottom.text2": " so you can see exactly how Taskey would work in your business.",
    "demo.links.what": "What is Taskey?",
    "demo.links.features": "All features",
    "demo.links.pricing": "Pricing",

    // Pricing Page
    "pricing.hero.badge": "TRANSPARENT. FAIR. FLEXIBLE.",
    "pricing.hero.title": "Pricing that fits your business",
    "pricing.hero.subtitle": "No hidden fees. All features included. Cancel anytime.",
    "pricing.hero.cta.trial": "Try free for 14 days",
    "pricing.hero.cta.demo": "Book a demo",
    "pricing.cancellation.label": "Cancellation period for START:",
    "pricing.cancellation.monthly": "Daily",
    "pricing.cancellation.quarterly": "Quarterly (–7%)",
    "pricing.cancellation.yearly": "Annual (–13%)",
    "pricing.card.start.name": "START",
    "pricing.card.start.tagline": "For small businesses",
    "pricing.card.start.desc": "The easy entry point for small businesses and sole traders.",
    "pricing.card.grow.name": "GROW",
    "pricing.card.grow.tagline": "Most popular",
    "pricing.card.grow.desc": "For growing teams – more control, more efficiency.",
    "pricing.card.scale.name": "SCALE",
    "pricing.card.scale.tagline": "For demanding businesses",
    "pricing.card.scale.desc": "For large businesses with complex requirements.",
    "pricing.card.perUser": "/ user / month",
    "pricing.card.cta.trial": "Start for free",
    "pricing.card.cta.demo": "Book a demo",
    "pricing.card.cancellation": "Cancellation:",
    "pricing.card.cancellation.daily": "daily",
    "pricing.card.cancellation.quarterly": "quarterly",
    "pricing.card.cancellation.yearly": "annually",
    "pricing.allfeatures.title": "Everything included – in every plan",
    "pricing.allfeatures.subtitle": "No feature gating. No hidden costs. All core features are included in every plan.",
    "pricing.allfeatures.datev.note": "DATEV / Lexware integration available as an optional add-on",
    "pricing.enterprise.badge": "FOR LARGE BUSINESSES",
    "pricing.enterprise.title": "ENTERPRISE",
    "pricing.enterprise.subtitle": "From 50 employees",
    "pricing.enterprise.desc": "Tailored solutions for leading organisations. Dedicated support, SLA guarantees and custom integrations.",
    "pricing.enterprise.cta1": "Learn more",
    "pricing.enterprise.cta2": "Request Enterprise",
    "pricing.nfc.badge": "ADD-ON",
    "pricing.nfc.title": "TASKEY NFC TAGS",
    "pricing.nfc.subtitle": "Physical NFC tags for your machines, tools and equipment",
    "pricing.nfc.starter.name": "Starter",
    "pricing.nfc.starter.tags": "10 NFC Tags",
    "pricing.nfc.pro.name": "Pro",
    "pricing.nfc.pro.tags": "50 NFC Tags",
    "pricing.nfc.business.name": "Business",
    "pricing.nfc.business.tags": "150 NFC Tags",
    "pricing.nfc.month": "/ month",
    "pricing.nfc.order": "Order now",
    "pricing.nfc.info.title": "Free replacement",
    "pricing.nfc.info.text": "Damaged or lost tags are replaced free of charge. Once per year.",
    "pricing.onboarding.badge": "SETUP SERVICE",
    "pricing.onboarding.title": "Ready to go. Done for You.",
    "pricing.onboarding.subtitle": "We set up Taskey completely for you – so you can start right away.",
    "pricing.onboarding.grow.name": "GROW Onboarding",
    "pricing.onboarding.grow.price": "€990",
    "pricing.onboarding.grow.desc": "Complete setup for GROW users",
    "pricing.onboarding.scale.name": "SCALE Onboarding",
    "pricing.onboarding.scale.price": "€2,490",
    "pricing.onboarding.scale.desc": "Enterprise setup for SCALE users",
    "pricing.onboarding.cta": "Request onboarding",
    "pricing.datev.badge": "ADD-ON",
    "pricing.datev.title": "DATEV / Lexware Integration",
    "pricing.datev.price": "€11.89 / month",
    "pricing.datev.forAll": "Available as add-on for any plan",
    "pricing.datev.cta": "Add now",
    "pricing.manager.badge": "PREMIUM SERVICE",
    "pricing.manager.title": "Taskey Premium Manager",
    "pricing.manager.subtitle": "Your personal expert for your business",
    "pricing.manager.price": "€239 / week",
    "pricing.manager.cta1": "Learn more",
    "pricing.manager.cta2": "Request now",
    "pricing.storage.title": "Need more storage?",
    "pricing.storage.subtitle": "Expand your storage flexibly as needed.",
    "pricing.storage.tier1": "+100 GB",
    "pricing.storage.tier2": "+500 GB",
    "pricing.storage.tier3": "+1 TB",
    "pricing.storage.month": "/ month",
    "pricing.storage.cta": "Add now",
    "pricing.faq.title": "Frequently asked pricing questions",
    "pricing.faq.1.q": "Is there a free trial?",
    "pricing.faq.1.a": "Yes! You can try Taskey free for 14 days – no credit card required.",
    "pricing.faq.2.q": "Can I switch plans?",
    "pricing.faq.2.a": "Yes, you can upgrade or downgrade at any time.",
    "pricing.faq.3.q": "What happens after the trial?",
    "pricing.faq.3.a": "After 14 days you choose a plan or the account is paused – no automatic charge.",
    "pricing.faq.4.q": "Are updates included?",
    "pricing.faq.4.a": "Yes, all updates are free and applied automatically.",
    "pricing.cta.title": "Ready to get started?",
    "pricing.cta.subtitle": "Start for free now and save an average of 25–30 hours per month.",
    "pricing.cta.trial": "Start free for 14 days",
    "pricing.cta.demo": "Book a demo",

    // Rollen Page
    "rollen.hero.title": "Roles & Permissions",
    "rollen.hero.subtitle": "Every role in Taskey is tailored to its tasks – from field staff to management",
    "rollen.overview.title": "An overview",
    "rollen.role.employee": "Employee",
    "rollen.role.employee.desc": "Works on-site with customers and documents the job",
    "rollen.role.specialist": "Specialist",
    "rollen.role.specialist.desc": "Plans, controls and manages from the office",
    "rollen.role.leader": "Leader",
    "rollen.role.leader.desc": "Runs the business and has full control",
    "rollen.cta.title": "The right role for everyone",
    "rollen.cta.subtitle": "Start now and give everyone on your team exactly the permissions they need.",
    "rollen.cta.btn": "Start for free",

    // Was ist Taskey Page
    "was.hero.title.prefix": "What is",
    "was.hero.title.main": "Taskey",
    "was.hero.subtitle": "More than software – a system for objectifying work",
    "was.principle.badge": "Core principle",
    "was.principle.title": "The core principle",
    "was.principle.not": "Taskey is not a time tracker, not a surveillance tool and not admin software.",
    "was.principle.is": "Taskey is a system for objectifying work",
    "was.principle.measurable": "Work becomes measurable, explainable and verifiable – without people constantly having to justify themselves.",
    "was.principle.facts": "Not feelings, assumptions or power dynamics decide – but traceable facts.",
    "was.principle.trust": "Taskey doesn't replace trust",
    "was.cta.title": "Ready to transform your business?",
    "was.cta.subtitle": "Start for free now and discover what Taskey can do for you.",
    "was.cta.trial": "Try free for 14 days",
    "was.cta.demo": "Book a demo",

    // Enterprise Page
    "enterprise.hero.title.prefix": "Taskey",
    "enterprise.hero.title.highlight": "Enterprise",
    "enterprise.hero.subtitle": "Tailored, exclusive solutions for leading organisations — available to selected partners only",
    "enterprise.hero.admission": "Admission by application & review only",
    "enterprise.hero.desc1": "We offer a strictly limited Enterprise programme. Applications are reviewed individually and only companies that meet our high requirements for size, security standards and business relevance are accepted.",
    "enterprise.hero.desc2": "Requirements may include: minimum size (100+ employees), demonstrable market leadership or strategic significance, and advanced integration requirements.",
    "enterprise.hero.note": "Note: Admission is subject to individual review.",
    "enterprise.when.title": "When is Enterprise right for you?",
    "enterprise.when.subtitle": "We recommend Enterprise for companies with unique requirements and strategic relevance",
    "enterprise.cta.apply": "Request Enterprise",
    "enterprise.cta.demo": "Book a demo",

    // Premium Manager Page
    "manager.hero.badge": "PREMIUM SERVICE",
    "manager.hero.title": "Taskey Premium Manager",
    "manager.hero.subtitle": "Your personal expert for your business",
    "manager.cta.request": "Request now",
    "manager.cta.demo": "Book a demo",
    "manager.price": "€239 / week",
  },

  tr: {
    // Navigation
    "nav.whatIsTaskey": "Taskey nedir?",
    "nav.features": "Özellikler",
    "nav.liveDemo": "Canlı Demo",
    "nav.pricing": "Fiyatlar",
    "nav.about": "Hakkımızda",
    "nav.support": "Destek",
    "nav.bookDemo": "Demo rezervasyonu",
    "nav.tryFree": "Ücretsiz dene",

    // Hero
    "hero.title": "Verimli işletmeler için 1 numaralı hizmet yönetim yazılımı",
    "hero.title.highlight": "1 numaralı",
    "hero.subtitle": "Ayda ortalama 25–30 saat tasarruf edin. 600'den fazla sektör için otomatik zaman takibi, akıllı iş planlaması ve dijital faturalandırma. Almanya'da üretildi, GDPR uyumlu.",
    "hero.subtitle.highlight": "ayda 25–30 saat",
    "hero.cta.demo": "Demo rezervasyonu",
    "hero.cta.trial": "14 gün ücretsiz dene",

    // FeaturePreview
    "features.badge": "Temel Özellikler",
    "features.title": "Taskey'in temelleri",
    "features.title.em": "temelleri",
    "features.subtitle": "İşletmenizi daha verimli, şeffaf ve karlı hale getiren üç temel sütun.",
    "features.1.title": "Otomatik Zaman Takibi",
    "features.1.desc": "Çalışma saatleri manuel giriş olmadan dijital olarak kaydedilir. Daha az evrak işi, hatasız faturalandırma ve tüm ekibiniz için tam şeffaflık.",
    "features.2.title": "Sezgisel İş Planlaması",
    "features.2.desc": "Projeleri, randevuları ve görev planlarını merkezi olarak yönetin. Rota optimizasyonu ve otomatik zamanlama, ekibinizin her zaman doğru yerde olmasını sağlar.",
    "features.3.title": "Finans & Muhasebe Özeti",
    "features.3.desc": "Faturaları doğrudan uygulamadan oluşturun ve gönderin. Gelir, bütçe ve maliyetler gerçek zamanlı – her proje için otomatik kârlılık analizi dahil.",

    // NFC Section
    "nfc.badge": "YENİLİK: NFC ETİKETLERİ",
    "nfc.title": "Yapıştır. Tara. Bil.",
    "nfc.subtitle": "İşletmenize dijital bir hafıza kazandırın. Her makine, her tesisat akıllı hale gelir.",
    "nfc.1.title": "Alet ve Makine Takibi",
    "nfc.1.desc": "Büyük şantiyelerde aletleri bir daha unutmayın. Her tarama GPS konumuyla kayıt altına alınır.",
    "nfc.2.title": "Ekipman için GPS Takibi",
    "nfc.2.desc": "Aletleri iş yerinde bir daha kaybetmeyin. Son tarama konumu haritada gösterilir.",
    "nfc.3.title": "Yasal Olarak Geçerli Kanıt",
    "nfc.3.desc": "Tarama zaman damgaları ekibinizin yerinde olduğunu ve kontrol yaptığını kanıtlar. Sigorta ve sorumluluk konularında mükemmel.",
    "nfc.4.title": "Bilgi Koruma",
    "nfc.4.desc": "En iyi ustanız emekliye mi gidiyor? Bilgi nesnede kalır — onun kafasında değil.",
    "nfc.stat1": "Sınırsız yeniden kullanım",
    "nfc.stat2": "Hizmet ömrü",
    "nfc.stat3": "Su geçirmez ve hava koşullarına dayanıklı",

    // iOS App Section
    "ios.badge": "Mobil Uygulama",
    "ios.title": "Taskey",
    "ios.title.highlight": "iOS için",
    "ios.subtitle": "İşleri yönetin, saatleri takip edin ve ekibinizi koordine edin – doğrudan iPhone veya iPad'inizden.",
    "ios.feature1.label": "Sezgisel Arayüz",
    "ios.feature1.desc": "Hemen anlaşılabilir net yapı – eğitime gerek yok.",
    "ios.feature2.label": "Çevrimdışı Çalışır",
    "ios.feature2.desc": "İnternet olmadan da çalışın – veriler tekrar bağlanınca otomatik senkronize olur.",
    "ios.feature3.label": "Anlık Bildirimler",
    "ios.feature3.desc": "İşler, saatler ve ekip değişikliklerine ilişkin gerçek zamanlı güncellemeler.",
    "ios.feature4.label": "Face ID & Touch ID",
    "ios.feature4.desc": "Saniyeler içinde güvenli erişim – şifre girişine gerek yok.",
    "ios.appstore": "App Store'dan indir",
    "ios.allFeatures": "Tüm özellikleri keşfet",
    "ios.socialProof": "Almanya'da {count}+ işletme tarafından kullanılıyor",

    // BusinessSize Section
    "biz.badge": "Her işletme için doğru çözüm",
    "biz.title": "Taskey",
    "biz.title.highlight": "sizinle büyür",
    "biz.card1.label": "1–5 çalışan",
    "biz.card1.text": "Küçük veya yeni kurulmuş bir işletme misiniz ve çalışma saatlerini, iş akışlarını ve iş günlerini daha verimli düzenlemek mi istiyorsunuz?",
    "biz.card2.label": "6–20 çalışan",
    "biz.card2.text": "İşletmeniz büyüyor mu ve genel bakışı kaybetmeden ekipleri, projeleri ve görev planlarını merkezi olarak yönetmek mi istiyorsunuz?",
    "biz.card3.label": "21–50 çalışan",
    "biz.card3.text": "Büyük bir şirket mi yönetiyorsunuz ve karmaşık yapılar, birden fazla ekip ve zorlu görev planlaması için ölçeklenebilir bir çözüme mi ihtiyaç duyuyorsunuz?",
    "biz.cta": "Planlara bakın →",

    // Testimonials
    "testimonials.title": "Hizmet sağlayıcılar Taskey'e güveniyor",
    "testimonials.subtitle": "Almanya genelinde {count}'dan fazla memnun işletme",
    "testimonials.1.text": "Taskey ile idari süremizi %70 oranında azalttık. Müşterilerimize daha fazla zaman kalıyor!",
    "testimonials.2.text": "Otomatik zaman takibi harika. Faturalamada artık unutulan saatler yok.",
    "testimonials.3.text": "Sonunda gerçekten kullanımı kolay bir yazılım. Ekibim hemen verimli olmaya başladı.",

    // FAQ
    "faq.title": "Sıkça Sorulan Sorular",
    "faq.subtitle": "Taskey hakkında bilmeniz gereken her şey",
    "faq.1.q": "Taskey ne kadar tutar?",
    "faq.1.a": "Taskey her işletme büyüklüğü için esnek fiyatlandırma planları sunar. Ayrıntılı bilgi için fiyat sayfamıza bakın.",
    "faq.2.q": "Taskey GDPR uyumlu mu?",
    "faq.2.a": "Evet, Taskey tamamen GDPR uyumludur. Verileriniz Almanya'daki sunucularda saklanır ve şifreli olarak iletilir.",
    "faq.3.q": "Eğitime ihtiyacım var mı?",
    "faq.3.a": "Hayır, Taskey o kadar sezgisel ki hemen başlayabilirsiniz. İsteğe bağlı ücretsiz başlangıç oturumları da sunuyoruz.",
    "faq.4.q": "Taskey çevrimdışı çalışır mı?",
    "faq.4.a": "Evet, mobil uygulama çevrimdışı da çalışır. Tekrar çevrimiçi olduğunuzda tüm veriler otomatik olarak senkronize edilir.",
    "faq.5.q": "Mevcut verileri içe aktarabilir miyim?",
    "faq.5.a": "Evet, yaygın formatlardan içe aktarmayı destekliyoruz ve diğer sistemlerden geçişte size yardım ediyoruz.",
    "faq.6.q": "Ne kadar hızlı başlayabilirim?",
    "faq.6.a": "Kayıt olduktan hemen sonra başlayabilirsiniz. Kurulum yalnızca birkaç dakika sürer.",
    "faq.7.q": "Minimum sözleşme süresi var mı?",
    "faq.7.a": "Hayır, aylık olarak iptal edebilirsiniz. Minimum süre yoktur.",
    "faq.8.q": "Taskey hangi desteği sunuyor?",
    "faq.8.a": "Mesai saatlerinde Almanca e-posta ve telefon desteği ile kapsamlı bir bilgi tabanı sunuyoruz.",
    "faq.9.q": "Taskey'i birden fazla lokasyon için kullanabilir miyim?",
    "faq.9.a": "Evet, Taskey merkezi genel bakışla çok lokasyonlu yönetimi destekler.",
    "faq.10.q": "Hangi cihazlar destekleniyor?",
    "faq.10.a": "Taskey tüm modern cihazlarda çalışır: iOS, Android, Windows, Mac ve tarayıcıda.",

    // Contact
    "contact.title": "Kullanım veya fiyat paketleri hakkında sorularınız mı var?",
    "contact.subtitle": "Sizin için buradayız – kişisel ve uzman",
    "contact.phone": "Telefon",
    "contact.email": "E-Posta",
    "contact.address": "Adres",
    "contact.cta.title": "İkna oldunuz mu?",
    "contact.cta.subtitle": "Ücretsiz başlayın ve ayda ortalama 25–30 saat tasarruf edin.",
    "contact.cta.highlight": "ayda 25–30 saat",
    "contact.cta.demo": "Demo rezervasyonu",
    "contact.cta.trial": "14 gün ücretsiz dene",

    // Footer
    "footer.tagline": "Almanya'dan 1 numaralı hizmet yönetim yazılımı. 600'den fazla sektör için otomatik zaman takibi, akıllı iş planlaması ve dijital faturalandırma.",
    "footer.col.product": "Ürün",
    "footer.col.company": "Şirket",
    "footer.col.legal": "Yasal",
    "footer.col.contact": "İletişim",
    "footer.link.features": "Özellikler",
    "footer.link.pricing": "Fiyatlar",
    "footer.link.bookDemo": "Demo rezervasyonu",
    "footer.link.about": "Hakkımızda",
    "footer.link.contact": "İletişim",
    "footer.link.support": "Destek",
    "footer.link.imprint": "Künye",
    "footer.link.privacy": "Gizlilik Politikası",
    "footer.link.agb": "Kullanım Koşulları",
    "footer.link.supportContact": "Destek & İletişim",
    "footer.rights": "Tüm hakları saklıdır.",
    "footer.cookie": "Çerez ayarları",
    "footer.madeIn": "🇩🇪 Almanya'da Üretildi",

    // Branchen
    "branchen.title": "Taskey'i hangi sektör için kullanmak istiyorsunuz?",
    "branchen.subtitle": "Taskey 600'den fazla sektöre uygundur – zanaattan tesis yönetimine kadar.",
    "branchen.search": "Sektör ara...",
    "branchen.noResults": "Sektör bulunamadı",
    "branchen.cta": "Demo rezervasyonu",
    "branchen.ctaText": "Bulamadınız mı? Bizimle iletişime geçin.",

    // About Page
    "about.hero.title": "Taskey Hakkında",
    "about.hero.subtitle": "Hizmet işletmelerine gerçekten yardımcı olan yazılım",
    "about.mission.p1": "Taskey, her türden hizmet işletmesinin günlük operasyonlarını kolaylaştırmak için geliştirildi. Manuel idari görevlere ne kadar zaman ve enerji harcandığını gördük – bu zamanın asıl işe ve müşterilere ayrılması gerekiyor. İster zanaat, ister tesis yönetimi, ister teknik hizmetler veya mobil hizmetler olsun – randevuların, işlerin ve personelin koordine edilmesi gereken her yerde Taskey çözümdür.",
    "about.mission.p2": "Misyonumuz, özellikle Alman işletmelerinin ihtiyaçlarına göre tasarlanmış en iyi ve en sezgisel hizmet yazılımını oluşturmaktır. Elektrik tesisatından bina temizliğine, etkinlik hizmetlerine kadar – Taskey gereksinimlerinizle birlikte büyür. Almanya'da üretildi, GDPR uyumlu ve hak ettiğiniz hizmetle.",
    "about.why.title": "Neden Taskey'i Geliştirdik",
    "about.why.problem.title": "Sorun",
    "about.why.problem.text": "Pek çok hizmet sağlayıcı, manuel süreçler, karmaşık elektronik tablolar ve karmaşık yazılımlarla değerli zamanını kaybediyor. Çalışma saatleri gidiyor, faturalar geç çıkıyor ve genel bakış eksik kalıyor.",
    "about.why.solution.title": "Çözümümüz",
    "about.why.solution.text": "Taskey ile gerçekten kullanımı kolay hepsi bir arada bir çözüm oluşturduk. Otomatik zaman takibi, akıllı planlama ve dijital iş akışları ayda ortalama 25–30 saat tasarruf sağlıyor – işinize geri dönen zaman.",
    "about.values.title": "Değerlerimiz",
    "about.values.1.title": "Sadelik",
    "about.values.1.text": "Yazılım günlük hayatı basitleştirmeli, karmaşıklaştırmamalı. Bu yüzden Taskey sezgisel ve eğitimsiz kullanılabilir.",
    "about.values.2.title": "Güvenlik",
    "about.values.2.text": "Verileriniz bizimle güvende. GDPR uyumlu, şifreli ve Almanya'daki sunucularda barındırılıyor.",
    "about.values.3.title": "Müşteri hizmetleri",
    "about.values.3.text": "Sizin için buradayız. Almanca destek, hızlı yanıtlar ve hattın diğer ucunda gerçek insanlarla.",
    "about.team.title": "Ekibimiz",
    "about.team.founders": "Kurucular",
    "about.team.team": "Ekip",
    "about.contact.title": "İletişim & Yasal",
    "about.contact.phone": "Telefon",
    "about.contact.email": "E-Posta",
    "about.contact.address": "Adres",
    "about.contact.more": "Daha fazla bilgiye",
    "about.contact.imprint": "Künye",
    "about.contact.and": "ve",
    "about.contact.privacy": "Gizlilik Politikası",

    // Demo Page
    "demo.badge": "Canlı demo mevcut",
    "demo.hero.title": "Taskey'i",
    "demo.hero.title.highlight": "canlı deneyimleyin",
    "demo.hero.subtitle": "Taskey'in işletmenizi nasıl dönüştürebileceğini keşfedin —",
    "demo.hero.subtitle.strong": "kayıt yok, taahhüt yok.",
    "demo.cta": "Demoyu şimdi deneyin",
    "demo.trust": "✓ Kredi kartı gerekmez · ✓ Anında erişim · ✓ Gerçekçi veriler",
    "demo.screenshots.label": "Önizleme",
    "demo.screenshots.title": "Taskey pratikte",
    "demo.screenshots.title.highlight": "böyle görünür",
    "demo.screenshots.title.suffix": "",
    "demo.benefits.label": "Neden demoyu deneyin?",
    "demo.benefits.title": "Kendiniz",
    "demo.benefits.title.highlight": "görün",
    "demo.benefit1.title": "Tam genel bakış",
    "demo.benefit1.desc": "Tüm özellikleri eylemde görün — gösterge paneli, işler, zaman takibi.",
    "demo.benefit2.title": "Kayıt yok",
    "demo.benefit2.desc": "Hesap olmadan anında erişim — sadece tıklayın ve başlayın.",
    "demo.benefit3.title": "Gerçek veriler",
    "demo.benefit3.desc": "Zanaattan gerçekçi örnek senaryolar.",
    "demo.benefit4.title": "100% Ücretsiz",
    "demo.benefit4.desc": "Gizli maliyet yok, kredi kartı gerekmez.",
    "demo.features.label": "Özellikler",
    "demo.features.title": "Demoda ne",
    "demo.features.title.highlight": "keşfedeceksiniz",
    "demo.feature1": "Gerçek zamanlı verilerle eksiksiz gösterge paneli",
    "demo.feature2": "İş ve proje yönetimi eylemde",
    "demo.feature3": "Otomatik zaman takibi ve personel yönetimi",
    "demo.feature4": "GPS takibi ve interaktif harita özelliği",
    "demo.feature5": "Raporlar, analizler ve değerlendirmeler",
    "demo.feature6": "Müşteri yönetimi ve iletişim",
    "demo.cta2": "Şimdi ücretsiz deneyin",
    "demo.bottom.text": "Demo,",
    "demo.bottom.strong": "gerçekçi örnek verilerle",
    "demo.bottom.text2": " çalışır — Taskey'in işletmenizde tam olarak nasıl çalışacağını göreceksiniz.",
    "demo.links.what": "Taskey nedir?",
    "demo.links.features": "Tüm özellikler",
    "demo.links.pricing": "Fiyatlar",

    // Pricing Page
    "pricing.hero.badge": "ŞEFFAF. ADIL. ESNEK.",
    "pricing.hero.title": "İşletmenize uygun fiyatlar",
    "pricing.hero.subtitle": "Gizli ücret yok. Tüm özellikler dahil. İstediğiniz zaman iptal edin.",
    "pricing.hero.cta.trial": "14 gün ücretsiz deneyin",
    "pricing.hero.cta.demo": "Demo rezervasyonu",
    "pricing.cancellation.label": "START için iptal süresi:",
    "pricing.cancellation.monthly": "Günlük",
    "pricing.cancellation.quarterly": "Üç aylık (–%7)",
    "pricing.cancellation.yearly": "Yıllık (–%13)",
    "pricing.card.start.name": "START",
    "pricing.card.start.tagline": "Küçük işletmeler için",
    "pricing.card.start.desc": "Küçük işletmeler ve serbest çalışanlar için kolay başlangıç noktası.",
    "pricing.card.grow.name": "GROW",
    "pricing.card.grow.tagline": "En popüler",
    "pricing.card.grow.desc": "Büyüyen ekipler için – daha fazla kontrol, daha fazla verimlilik.",
    "pricing.card.scale.name": "SCALE",
    "pricing.card.scale.tagline": "Zorlu işletmeler için",
    "pricing.card.scale.desc": "Karmaşık gereksinimleri olan büyük işletmeler için.",
    "pricing.card.perUser": "/ kullanıcı / ay",
    "pricing.card.cta.trial": "Ücretsiz başla",
    "pricing.card.cta.demo": "Demo rezervasyonu",
    "pricing.card.cancellation": "İptal:",
    "pricing.card.cancellation.daily": "günlük",
    "pricing.card.cancellation.quarterly": "üç aylık",
    "pricing.card.cancellation.yearly": "yıllık",
    "pricing.allfeatures.title": "Her şey dahil – her pakette",
    "pricing.allfeatures.subtitle": "Özellik kısıtlaması yok. Gizli maliyet yok. Tüm temel özellikler her pakette dahil.",
    "pricing.allfeatures.datev.note": "DATEV / Lexware entegrasyonu isteğe bağlı eklenti olarak mevcut",
    "pricing.enterprise.badge": "BÜYÜK İŞLETMELER İÇİN",
    "pricing.enterprise.title": "ENTERPRISE",
    "pricing.enterprise.subtitle": "50+ çalışandan itibaren",
    "pricing.enterprise.desc": "Lider kuruluşlar için özel çözümler. Özel destek, SLA garantileri ve özel entegrasyonlar.",
    "pricing.enterprise.cta1": "Daha fazla bilgi",
    "pricing.enterprise.cta2": "Enterprise talep et",
    "pricing.nfc.badge": "EKLENTİ",
    "pricing.nfc.title": "TASKEY NFC ETİKETLERİ",
    "pricing.nfc.subtitle": "Makineleriniz, aletleriniz ve ekipmanlarınız için fiziksel NFC etiketleri",
    "pricing.nfc.starter.name": "Başlangıç",
    "pricing.nfc.starter.tags": "10 NFC Etiketi",
    "pricing.nfc.pro.name": "Pro",
    "pricing.nfc.pro.tags": "50 NFC Etiketi",
    "pricing.nfc.business.name": "Business",
    "pricing.nfc.business.tags": "150 NFC Etiketi",
    "pricing.nfc.month": "/ ay",
    "pricing.nfc.order": "Şimdi sipariş ver",
    "pricing.nfc.info.title": "Ücretsiz değiştirme",
    "pricing.nfc.info.text": "Hasarlı veya kayıp etiketler ücretsiz değiştirilir. Yılda bir kez.",
    "pricing.onboarding.badge": "KURULUM HİZMETİ",
    "pricing.onboarding.title": "Anahtar teslim. Sizin İçin Yapıldı.",
    "pricing.onboarding.subtitle": "Taskey'i sizin için tamamen kuruyoruz – böylece hemen başlayabilirsiniz.",
    "pricing.onboarding.grow.name": "GROW Onboarding",
    "pricing.onboarding.grow.price": "990 €",
    "pricing.onboarding.grow.desc": "GROW kullanıcıları için tam kurulum",
    "pricing.onboarding.scale.name": "SCALE Onboarding",
    "pricing.onboarding.scale.price": "2.490 €",
    "pricing.onboarding.scale.desc": "SCALE kullanıcıları için enterprise kurulum",
    "pricing.onboarding.cta": "Onboarding talep et",
    "pricing.datev.badge": "EKLENTİ",
    "pricing.datev.title": "DATEV / Lexware Entegrasyonu",
    "pricing.datev.price": "11,89 € / ay",
    "pricing.datev.forAll": "Her pakete eklenebilir",
    "pricing.datev.cta": "Şimdi ekle",
    "pricing.manager.badge": "PREMİUM HİZMET",
    "pricing.manager.title": "Taskey Premium Manager",
    "pricing.manager.subtitle": "İşletmeniz için kişisel uzmanınız",
    "pricing.manager.price": "239 € / hafta",
    "pricing.manager.cta1": "Daha fazla bilgi",
    "pricing.manager.cta2": "Şimdi talep et",
    "pricing.storage.title": "Daha fazla depolama alanına mı ihtiyacınız var?",
    "pricing.storage.subtitle": "Depolama alanınızı ihtiyaca göre esnek şekilde genişletin.",
    "pricing.storage.tier1": "+100 GB",
    "pricing.storage.tier2": "+500 GB",
    "pricing.storage.tier3": "+1 TB",
    "pricing.storage.month": "/ ay",
    "pricing.storage.cta": "Şimdi ekle",
    "pricing.faq.title": "Sık sorulan fiyatlandırma soruları",
    "pricing.faq.1.q": "Ücretsiz deneme var mı?",
    "pricing.faq.1.a": "Evet! Taskey'i 14 gün ücretsiz deneyebilirsiniz – kredi kartı gerekmez.",
    "pricing.faq.2.q": "Paketi değiştirebilir miyim?",
    "pricing.faq.2.a": "Evet, istediğiniz zaman yükseltme veya düşürme yapabilirsiniz.",
    "pricing.faq.3.q": "Deneme süresinden sonra ne olur?",
    "pricing.faq.3.a": "14 günden sonra bir paket seçersiniz veya hesap duraklatılır – otomatik ücretlendirme yok.",
    "pricing.faq.4.q": "Güncellemeler dahil mi?",
    "pricing.faq.4.a": "Evet, tüm güncellemeler ücretsizdir ve otomatik olarak uygulanır.",
    "pricing.cta.title": "Başlamaya hazır mısınız?",
    "pricing.cta.subtitle": "Şimdi ücretsiz başlayın ve ayda ortalama 25–30 saat tasarruf edin.",
    "pricing.cta.trial": "14 gün ücretsiz başla",
    "pricing.cta.demo": "Demo rezervasyonu",

    // Rollen Page
    "rollen.hero.title": "Roller & İzinler",
    "rollen.hero.subtitle": "Taskey'deki her rol görevlerine göre tasarlanmıştır – saha personelinden yönetime kadar",
    "rollen.overview.title": "Genel bakış",
    "rollen.role.employee": "Çalışan",
    "rollen.role.employee.desc": "Müşteride çalışır ve işi belgeler",
    "rollen.role.specialist": "Uzman",
    "rollen.role.specialist.desc": "Ofisten planlar, kontrol eder ve yönetir",
    "rollen.role.leader": "Lider",
    "rollen.role.leader.desc": "İşletmeyi yönetir ve tam kontrole sahiptir",
    "rollen.cta.title": "Herkes için doğru rol",
    "rollen.cta.subtitle": "Şimdi başlayın ve ekibinizdeki herkese tam olarak ihtiyaç duydukları izinleri verin.",
    "rollen.cta.btn": "Ücretsiz başla",

    // Was ist Taskey Page
    "was.hero.title.prefix": "Taskey",
    "was.hero.title.main": "nedir",
    "was.hero.subtitle": "Sadece yazılım değil – işi nesnelleştiren bir sistem",
    "was.principle.badge": "Temel ilke",
    "was.principle.title": "Temel ilke",
    "was.principle.not": "Taskey bir zaman takip aracı değil, bir gözetleme aracı değil ve bir yönetim yazılımı değildir.",
    "was.principle.is": "Taskey, işi nesnelleştiren bir sistemdir",
    "was.principle.measurable": "İş ölçülebilir, açıklanabilir ve kanıtlanabilir hale gelir – insanların sürekli kendilerini haklı çıkarmaları gerekmez.",
    "was.principle.facts": "Hisler, varsayımlar veya güç dengeleri değil – takip edilebilir gerçekler karar verir.",
    "was.principle.trust": "Taskey güveni yerine koymaz",
    "was.cta.title": "İşletmenizi dönüştürmeye hazır mısınız?",
    "was.cta.subtitle": "Şimdi ücretsiz başlayın ve Taskey'in sizin için neler yapabileceğini keşfedin.",
    "was.cta.trial": "14 gün ücretsiz dene",
    "was.cta.demo": "Demo rezervasyonu",

    // Enterprise Page
    "enterprise.hero.title.prefix": "Taskey",
    "enterprise.hero.title.highlight": "Enterprise",
    "enterprise.hero.subtitle": "Lider kuruluşlar için özel, münhasır çözümler — yalnızca seçili ortaklar için mevcut",
    "enterprise.hero.admission": "Yalnızca başvuru ve inceleme ile kabul",
    "enterprise.hero.desc1": "Sıkı sınırlı bir Enterprise programı sunuyoruz. Başvurular bireysel olarak incelenir ve yalnızca büyüklük, güvenlik standartları ve iş alaka düzeyi konusundaki yüksek gereksinimlerimizi karşılayan şirketler kabul edilir.",
    "enterprise.hero.desc2": "Gereksinimler şunları içerebilir: minimum büyüklük (100+ çalışan), kanıtlanabilir pazar liderliği veya stratejik önem ve gelişmiş entegrasyon gereksinimleri.",
    "enterprise.hero.note": "Not: Kabul bireysel incelemeye tabidir.",
    "enterprise.when.title": "Enterprise ne zaman sizin için doğrudur?",
    "enterprise.when.subtitle": "Benzersiz gereksinimleri ve stratejik önemi olan şirketler için Enterprise'ı öneriyoruz",
    "enterprise.cta.apply": "Enterprise talep et",
    "enterprise.cta.demo": "Demo rezervasyonu",

    // Premium Manager Page
    "manager.hero.badge": "PREMİUM HİZMET",
    "manager.hero.title": "Taskey Premium Manager",
    "manager.hero.subtitle": "İşletmeniz için kişisel uzmanınız",
    "manager.cta.request": "Şimdi talep et",
    "manager.cta.demo": "Demo rezervasyonu",
    "manager.price": "239 € / hafta",
  },

  fr: {
    // Navigation
    "nav.whatIsTaskey": "Qu'est-ce que Taskey ?",
    "nav.features": "Fonctionnalités",
    "nav.liveDemo": "Démo en direct",
    "nav.pricing": "Tarifs",
    "nav.about": "À propos",
    "nav.support": "Support",
    "nav.bookDemo": "Réserver une démo",
    "nav.tryFree": "Essai gratuit",

    // Hero
    "hero.title": "Le logiciel de gestion n°1 pour les entreprises de services efficaces",
    "hero.title.highlight": "n°1",
    "hero.subtitle": "Économisez en moyenne 25 à 30 heures par mois. Pointage automatique, planification intelligente et facturation numérique pour plus de 600 secteurs. Made in Germany, conforme RGPD.",
    "hero.subtitle.highlight": "25–30 h par mois",
    "hero.cta.demo": "Réserver une démo",
    "hero.cta.trial": "Essai gratuit 14 jours",

    // FeaturePreview
    "features.badge": "Fonctionnalités clés",
    "features.title": "Les piliers de Taskey",
    "features.title.em": "de",
    "features.subtitle": "Trois piliers qui rendent votre entreprise plus efficace, transparente et rentable.",
    "features.1.title": "Pointage automatique",
    "features.1.desc": "Les heures de travail sont enregistrées numériquement sans saisie manuelle. Moins de paperasse, facturation sans erreur et transparence totale pour toute votre équipe.",
    "features.2.title": "Planification intuitive",
    "features.2.desc": "Gérez centralement projets, rendez-vous et plannings d'intervention. L'optimisation des itinéraires et la planification automatique garantissent que votre équipe est toujours au bon endroit au bon moment.",
    "features.3.title": "Aperçu finances & comptabilité",
    "features.3.desc": "Créez et envoyez des factures directement depuis l'application. Chiffre d'affaires, budget et coûts en temps réel – avec analyse automatique de la rentabilité pour chaque projet.",

    // NFC Section
    "nfc.badge": "INNOVATION : TAGS NFC",
    "nfc.title": "Coller. Scanner. Savoir.",
    "nfc.subtitle": "Dotez votre entreprise d'une mémoire numérique. Chaque machine, chaque installation devient intelligente.",
    "nfc.1.title": "Suivi outils & machines",
    "nfc.1.desc": "Ne perdez plus jamais vos outils sur un grand chantier. Chaque scan est enregistré avec la position GPS.",
    "nfc.2.title": "GPS pour équipements",
    "nfc.2.desc": "Ne perdez plus vos outils sur le chantier. Le dernier emplacement scanné est affiché sur la carte.",
    "nfc.3.title": "Preuve juridiquement valable",
    "nfc.3.desc": "Les horodatages de scan prouvent la présence de votre équipe et les contrôles effectués. Idéal pour les assurances et la responsabilité.",
    "nfc.4.title": "Préservation des savoirs",
    "nfc.4.desc": "Votre meilleur technicien part à la retraite ? Le savoir reste sur l'objet — pas dans sa tête.",
    "nfc.stat1": "Réutilisation illimitée",
    "nfc.stat2": "Durée de vie",
    "nfc.stat3": "Étanche & résistant aux intempéries",

    // iOS App Section
    "ios.badge": "Application mobile",
    "ios.title": "Taskey pour",
    "ios.title.highlight": "iOS",
    "ios.subtitle": "Gérez vos missions, suivez les heures et coordonnez votre équipe – directement depuis votre iPhone ou iPad.",
    "ios.feature1.label": "Interface intuitive",
    "ios.feature1.desc": "Structure claire, compréhensible immédiatement – sans formation.",
    "ios.feature2.label": "Fonctionne hors ligne",
    "ios.feature2.desc": "Travaillez sans réseau – les données se synchronisent automatiquement.",
    "ios.feature3.label": "Notifications push",
    "ios.feature3.desc": "Mises à jour en temps réel sur les missions, les heures et les changements d'équipe.",
    "ios.feature4.label": "Face ID & Touch ID",
    "ios.feature4.desc": "Accès sécurisé en quelques secondes – sans saisie de mot de passe.",
    "ios.appstore": "Télécharger sur l'App Store",
    "ios.allFeatures": "Découvrir toutes les fonctionnalités",
    "ios.socialProof": "Utilisé par {count}+ entreprises en Allemagne",

    // BusinessSize Section
    "biz.badge": "La bonne solution pour chaque entreprise",
    "biz.title": "Taskey grandit",
    "biz.title.highlight": "avec vous",
    "biz.card1.label": "1–5 employés",
    "biz.card1.text": "Vous gérez une petite entreprise ou venez de démarrer et souhaitez organiser plus efficacement les horaires, les processus et les journées de travail ?",
    "biz.card2.label": "6–20 employés",
    "biz.card2.text": "Votre entreprise grandit et vous souhaitez gérer centralement équipes, projets et plannings – sans perdre la vue d'ensemble ?",
    "biz.card3.label": "21–50 employés",
    "biz.card3.text": "Vous dirigez une grande entreprise et avez besoin d'une solution évolutive pour des structures complexes, plusieurs équipes et une planification exigeante ?",
    "biz.cta": "Voir les offres →",

    // Testimonials
    "testimonials.title": "Les prestataires de services font confiance à Taskey",
    "testimonials.subtitle": "Plus de {count} entreprises satisfaites dans toute l'Allemagne",
    "testimonials.1.text": "Avec Taskey, nous avons réduit notre temps administratif de 70 %. Plus de temps pour nos clients !",
    "testimonials.2.text": "Le pointage automatique est génial. Plus aucune heure oubliée lors de la facturation.",
    "testimonials.3.text": "Enfin un logiciel vraiment simple à utiliser. Mon équipe était productive dès le premier jour.",

    // FAQ
    "faq.title": "Questions fréquentes",
    "faq.subtitle": "Tout ce que vous devez savoir sur Taskey",
    "faq.1.q": "Combien coûte Taskey ?",
    "faq.1.a": "Taskey propose des formules tarifaires flexibles pour chaque taille d'entreprise. Consultez notre page tarifs pour des informations détaillées.",
    "faq.2.q": "Taskey est-il conforme au RGPD ?",
    "faq.2.a": "Oui, Taskey est entièrement conforme au RGPD. Vos données sont hébergées sur des serveurs allemands et transmises de manière chiffrée.",
    "faq.3.q": "Ai-je besoin d'une formation ?",
    "faq.3.a": "Non, Taskey est si intuitif que vous pouvez commencer immédiatement. Nous proposons également des sessions d'onboarding gratuites en option.",
    "faq.4.q": "Taskey fonctionne-t-il hors ligne ?",
    "faq.4.a": "Oui, l'application mobile fonctionne aussi hors ligne. Toutes les données sont synchronisées automatiquement dès que vous êtes de nouveau connecté.",
    "faq.5.q": "Puis-je importer des données existantes ?",
    "faq.5.a": "Oui, nous supportons l'import depuis les formats courants et vous aidons à migrer depuis d'autres systèmes.",
    "faq.6.q": "À quelle vitesse puis-je démarrer ?",
    "faq.6.a": "Vous pouvez démarrer immédiatement après l'inscription. La configuration ne prend que quelques minutes.",
    "faq.7.q": "Y a-t-il une durée d'engagement minimale ?",
    "faq.7.a": "Non, vous pouvez résilier mensuellement. Il n'y a pas de durée minimale.",
    "faq.8.q": "Quel support Taskey propose-t-il ?",
    "faq.8.a": "Nous offrons un support par e-mail et par téléphone pendant les heures d'ouverture, ainsi qu'une base de connaissances complète.",
    "faq.9.q": "Puis-je utiliser Taskey sur plusieurs sites ?",
    "faq.9.a": "Oui, Taskey prend en charge la gestion multi-sites avec une vue d'ensemble centralisée.",
    "faq.10.q": "Quels appareils sont pris en charge ?",
    "faq.10.a": "Taskey fonctionne sur tous les appareils modernes : iOS, Android, Windows, Mac et dans le navigateur.",

    // Contact
    "contact.title": "Des questions sur l'utilisation ou les forfaits ?",
    "contact.subtitle": "Nous sommes là pour vous – personnellement et avec expertise",
    "contact.phone": "Téléphone",
    "contact.email": "E-mail",
    "contact.address": "Adresse",
    "contact.cta.title": "Convaincu ?",
    "contact.cta.subtitle": "Démarrez gratuitement et économisez en moyenne 25 à 30 heures par mois.",
    "contact.cta.highlight": "25–30 h par mois",
    "contact.cta.demo": "Réserver une démo",
    "contact.cta.trial": "Essai gratuit 14 jours",

    // Footer
    "footer.tagline": "Le logiciel de gestion de services n°1 d'Allemagne. Pointage automatique, planification intelligente et facturation numérique pour plus de 600 secteurs.",
    "footer.col.product": "Produit",
    "footer.col.company": "Entreprise",
    "footer.col.legal": "Mentions légales",
    "footer.col.contact": "Contact",
    "footer.link.features": "Fonctionnalités",
    "footer.link.pricing": "Tarifs",
    "footer.link.bookDemo": "Réserver une démo",
    "footer.link.about": "À propos",
    "footer.link.contact": "Contact",
    "footer.link.support": "Support",
    "footer.link.imprint": "Mentions légales",
    "footer.link.privacy": "Politique de confidentialité",
    "footer.link.agb": "CGU",
    "footer.link.supportContact": "Support & Contact",
    "footer.rights": "Tous droits réservés.",
    "footer.cookie": "Paramètres des cookies",
    "footer.madeIn": "🇩🇪 Fabriqué en Allemagne",

    // Branchen
    "branchen.title": "Pour quel secteur souhaitez-vous utiliser Taskey ?",
    "branchen.subtitle": "Taskey convient à plus de 600 secteurs – de l'artisanat à la gestion de facilities.",
    "branchen.search": "Rechercher un secteur...",
    "branchen.noResults": "Aucun secteur trouvé",
    "branchen.cta": "Réserver une démo",
    "branchen.ctaText": "Introuvable ? Contactez-nous.",

    // About Page
    "about.hero.title": "À propos de Taskey",
    "about.hero.subtitle": "Le logiciel qui aide vraiment les entreprises de services",
    "about.mission.p1": "Taskey a été conçu pour faciliter le quotidien des entreprises de services de toutes sortes. Nous avons constaté combien de temps et d'énergie sont consacrés aux tâches administratives manuelles – du temps qui serait mieux investi dans le travail réel et les clients. Qu'il s'agisse de l'artisanat, de la gestion de facilities, de services techniques ou de services mobiles – partout où des rendez-vous, des missions et des équipes doivent être coordonnés, Taskey est la solution.",
    "about.mission.p2": "Notre mission est de créer le meilleur logiciel de gestion de services le plus intuitif, spécialement conçu pour les besoins des entreprises allemandes. De l'installation électrique au nettoyage de bâtiments en passant par les services événementiels – Taskey grandit avec vos exigences. Made in Germany, conforme RGPD et avec le service que vous méritez.",
    "about.why.title": "Pourquoi nous avons créé Taskey",
    "about.why.problem.title": "Le problème",
    "about.why.problem.text": "Trop de prestataires de services perdent un temps précieux avec des processus manuels, des tableurs illisibles et des logiciels compliqués. Les heures de travail disparaissent, les factures partent en retard et la vue d'ensemble manque.",
    "about.why.solution.title": "Notre solution",
    "about.why.solution.text": "Avec Taskey, nous avons créé une solution tout-en-un vraiment simple à utiliser. Le pointage automatique, la planification intelligente et les processus numériques économisent en moyenne 25–30 heures par mois – du temps que vous récupérez pour votre activité.",
    "about.values.title": "Nos valeurs",
    "about.values.1.title": "Simplicité",
    "about.values.1.text": "Un logiciel doit simplifier le quotidien, pas le compliquer. C'est pourquoi Taskey est intuitif et utilisable sans formation.",
    "about.values.2.title": "Sécurité",
    "about.values.2.text": "Vos données sont en sécurité chez nous. Conforme RGPD, chiffré et hébergé sur des serveurs allemands.",
    "about.values.3.title": "Service client",
    "about.values.3.text": "Nous sommes là pour vous. Avec un support francophone, des réponses rapides et de vraies personnes au bout du fil.",
    "about.team.title": "Notre équipe",
    "about.team.founders": "Fondateurs",
    "about.team.team": "Équipe",
    "about.contact.title": "Contact & Mentions légales",
    "about.contact.phone": "Téléphone",
    "about.contact.email": "E-mail",
    "about.contact.address": "Adresse",
    "about.contact.more": "Vous trouverez de plus amples informations dans nos",
    "about.contact.imprint": "Mentions légales",
    "about.contact.and": "et notre",
    "about.contact.privacy": "Politique de confidentialité",

    // Demo Page
    "demo.badge": "Démo en direct disponible",
    "demo.hero.title": "Découvrez Taskey",
    "demo.hero.title.highlight": "en direct",
    "demo.hero.subtitle": "Découvrez comment Taskey peut révolutionner votre entreprise —",
    "demo.hero.subtitle.strong": "sans inscription, sans engagement.",
    "demo.cta": "Essayer la démo maintenant",
    "demo.trust": "✓ Aucune carte bancaire requise · ✓ Accès instantané · ✓ Données réalistes",
    "demo.screenshots.label": "Aperçu",
    "demo.screenshots.title": "Voici à quoi ressemble Taskey",
    "demo.screenshots.title.highlight": "en pratique",
    "demo.screenshots.title.suffix": "",
    "demo.benefits.label": "Pourquoi essayer la démo ?",
    "demo.benefits.title": "Jugez par",
    "demo.benefits.title.highlight": "vous-même",
    "demo.benefit1.title": "Vue d'ensemble complète",
    "demo.benefit1.desc": "Voyez toutes les fonctionnalités en action — tableau de bord, missions, pointage.",
    "demo.benefit2.title": "Sans inscription",
    "demo.benefit2.desc": "Accès instantané sans compte — cliquez et commencez.",
    "demo.benefit3.title": "Données réelles",
    "demo.benefit3.desc": "Scénarios d'exemple réalistes issus du terrain.",
    "demo.benefit4.title": "100% Gratuit",
    "demo.benefit4.desc": "Aucun frais caché, aucune carte bancaire requise.",
    "demo.features.label": "Fonctionnalités",
    "demo.features.title": "Ce que vous découvrirez",
    "demo.features.title.highlight": "dans la démo",
    "demo.feature1": "Tableau de bord complet avec données en temps réel",
    "demo.feature2": "Gestion des missions et projets en action",
    "demo.feature3": "Pointage automatique et gestion du personnel",
    "demo.feature4": "GPS et fonctionnalité de carte interactive",
    "demo.feature5": "Rapports, analyses et évaluations",
    "demo.feature6": "Gestion des clients et communication",
    "demo.cta2": "Essayer gratuitement maintenant",
    "demo.bottom.text": "La démo fonctionne avec",
    "demo.bottom.strong": "des données d'exemple réalistes",
    "demo.bottom.text2": " pour que vous puissiez voir exactement comment Taskey fonctionnerait dans votre entreprise.",
    "demo.links.what": "Qu'est-ce que Taskey ?",
    "demo.links.features": "Toutes les fonctionnalités",
    "demo.links.pricing": "Tarifs",

    // Pricing Page
    "pricing.hero.badge": "TRANSPARENT. ÉQUITABLE. FLEXIBLE.",
    "pricing.hero.title": "Des tarifs adaptés à votre entreprise",
    "pricing.hero.subtitle": "Pas de frais cachés. Toutes les fonctionnalités incluses. Résiliation à tout moment.",
    "pricing.hero.cta.trial": "Essai gratuit 14 jours",
    "pricing.hero.cta.demo": "Réserver une démo",
    "pricing.cancellation.label": "Préavis de résiliation pour START :",
    "pricing.cancellation.monthly": "Quotidien",
    "pricing.cancellation.quarterly": "Trimestriel (–7 %)",
    "pricing.cancellation.yearly": "Annuel (–13 %)",
    "pricing.card.start.name": "START",
    "pricing.card.start.tagline": "Pour les petites entreprises",
    "pricing.card.start.desc": "Le point d'entrée facile pour les petites entreprises et les travailleurs indépendants.",
    "pricing.card.grow.name": "GROW",
    "pricing.card.grow.tagline": "Le plus populaire",
    "pricing.card.grow.desc": "Pour les équipes en croissance – plus de contrôle, plus d'efficacité.",
    "pricing.card.scale.name": "SCALE",
    "pricing.card.scale.tagline": "Pour les entreprises exigeantes",
    "pricing.card.scale.desc": "Pour les grandes entreprises aux exigences complexes.",
    "pricing.card.perUser": "/ utilisateur / mois",
    "pricing.card.cta.trial": "Commencer gratuitement",
    "pricing.card.cta.demo": "Réserver une démo",
    "pricing.card.cancellation": "Résiliation :",
    "pricing.card.cancellation.daily": "quotidienne",
    "pricing.card.cancellation.quarterly": "trimestrielle",
    "pricing.card.cancellation.yearly": "annuelle",
    "pricing.allfeatures.title": "Tout inclus – dans chaque forfait",
    "pricing.allfeatures.subtitle": "Pas de restriction de fonctionnalités. Pas de coûts cachés. Toutes les fonctionnalités de base incluses dans chaque forfait.",
    "pricing.allfeatures.datev.note": "Intégration DATEV / Lexware disponible en option",
    "pricing.enterprise.badge": "POUR LES GRANDES ENTREPRISES",
    "pricing.enterprise.title": "ENTERPRISE",
    "pricing.enterprise.subtitle": "À partir de 50 collaborateurs",
    "pricing.enterprise.desc": "Solutions sur mesure pour les organisations leaders. Support dédié, garanties SLA et intégrations personnalisées.",
    "pricing.enterprise.cta1": "En savoir plus",
    "pricing.enterprise.cta2": "Demander Enterprise",
    "pricing.nfc.badge": "ADD-ON",
    "pricing.nfc.title": "TAGS NFC TASKEY",
    "pricing.nfc.subtitle": "Tags NFC physiques pour vos machines, outils et équipements",
    "pricing.nfc.starter.name": "Starter",
    "pricing.nfc.starter.tags": "10 tags NFC",
    "pricing.nfc.pro.name": "Pro",
    "pricing.nfc.pro.tags": "50 tags NFC",
    "pricing.nfc.business.name": "Business",
    "pricing.nfc.business.tags": "150 tags NFC",
    "pricing.nfc.month": "/ mois",
    "pricing.nfc.order": "Commander maintenant",
    "pricing.nfc.info.title": "Remplacement gratuit",
    "pricing.nfc.info.text": "Les tags endommagés ou perdus sont remplacés gratuitement. Une fois par an.",
    "pricing.onboarding.badge": "SERVICE D'INSTALLATION",
    "pricing.onboarding.title": "Clé en main. Fait pour vous.",
    "pricing.onboarding.subtitle": "Nous configurons Taskey entièrement pour vous – pour que vous puissiez démarrer immédiatement.",
    "pricing.onboarding.grow.name": "Onboarding GROW",
    "pricing.onboarding.grow.price": "990 €",
    "pricing.onboarding.grow.desc": "Configuration complète pour les utilisateurs GROW",
    "pricing.onboarding.scale.name": "Onboarding SCALE",
    "pricing.onboarding.scale.price": "2 490 €",
    "pricing.onboarding.scale.desc": "Configuration enterprise pour les utilisateurs SCALE",
    "pricing.onboarding.cta": "Demander l'onboarding",
    "pricing.datev.badge": "ADD-ON",
    "pricing.datev.title": "Intégration DATEV / Lexware",
    "pricing.datev.price": "11,89 € / mois",
    "pricing.datev.forAll": "Disponible en add-on pour tous les forfaits",
    "pricing.datev.cta": "Ajouter maintenant",
    "pricing.manager.badge": "SERVICE PREMIUM",
    "pricing.manager.title": "Taskey Premium Manager",
    "pricing.manager.subtitle": "Votre expert personnel pour votre entreprise",
    "pricing.manager.price": "239 € / semaine",
    "pricing.manager.cta1": "En savoir plus",
    "pricing.manager.cta2": "Demander maintenant",
    "pricing.storage.title": "Besoin de plus de stockage ?",
    "pricing.storage.subtitle": "Étendez votre espace de stockage de façon flexible selon vos besoins.",
    "pricing.storage.tier1": "+100 Go",
    "pricing.storage.tier2": "+500 Go",
    "pricing.storage.tier3": "+1 To",
    "pricing.storage.month": "/ mois",
    "pricing.storage.cta": "Ajouter maintenant",
    "pricing.faq.title": "Questions fréquentes sur les tarifs",
    "pricing.faq.1.q": "Y a-t-il un essai gratuit ?",
    "pricing.faq.1.a": "Oui ! Vous pouvez essayer Taskey gratuitement pendant 14 jours – sans carte bancaire.",
    "pricing.faq.2.q": "Puis-je changer de forfait ?",
    "pricing.faq.2.a": "Oui, vous pouvez passer à un forfait supérieur ou inférieur à tout moment.",
    "pricing.faq.3.q": "Que se passe-t-il après l'essai ?",
    "pricing.faq.3.a": "Après 14 jours, vous choisissez un forfait ou le compte est mis en pause – aucun prélèvement automatique.",
    "pricing.faq.4.q": "Les mises à jour sont-elles incluses ?",
    "pricing.faq.4.a": "Oui, toutes les mises à jour sont gratuites et appliquées automatiquement.",
    "pricing.cta.title": "Prêt à démarrer ?",
    "pricing.cta.subtitle": "Commencez gratuitement et économisez en moyenne 25 à 30 heures par mois.",
    "pricing.cta.trial": "Démarrer gratuitement 14 jours",
    "pricing.cta.demo": "Réserver une démo",

    // Rollen Page
    "rollen.hero.title": "Rôles & Autorisations",
    "rollen.hero.subtitle": "Chaque rôle dans Taskey est adapté à ses tâches – du terrain à la direction",
    "rollen.overview.title": "Vue d'ensemble",
    "rollen.role.employee": "Employé",
    "rollen.role.employee.desc": "Travaille chez le client et documente la mission",
    "rollen.role.specialist": "Spécialiste",
    "rollen.role.specialist.desc": "Planifie, contrôle et gère depuis le bureau",
    "rollen.role.leader": "Leader",
    "rollen.role.leader.desc": "Dirige l'entreprise et a le contrôle total",
    "rollen.cta.title": "Le bon rôle pour chacun",
    "rollen.cta.subtitle": "Démarrez maintenant et donnez à chaque membre de votre équipe exactement les autorisations dont il a besoin.",
    "rollen.cta.btn": "Commencer gratuitement",

    // Was ist Taskey Page
    "was.hero.title.prefix": "Qu'est-ce que",
    "was.hero.title.main": "Taskey",
    "was.hero.subtitle": "Plus qu'un logiciel – un système pour objectiver le travail",
    "was.principle.badge": "Principe fondamental",
    "was.principle.title": "Le principe fondamental",
    "was.principle.not": "Taskey n'est pas un outil de pointage, pas un outil de surveillance et pas un logiciel de gestion.",
    "was.principle.is": "Taskey est un système pour objectiver le travail",
    "was.principle.measurable": "Le travail devient mesurable, explicable et vérifiable – sans que les gens aient à se justifier constamment.",
    "was.principle.facts": "Ce ne sont pas les sentiments, les suppositions ou les rapports de force qui décident, mais des faits traçables.",
    "was.principle.trust": "Taskey ne remplace pas la confiance",
    "was.cta.title": "Prêt à transformer votre entreprise ?",
    "was.cta.subtitle": "Démarrez gratuitement et découvrez ce que Taskey peut faire pour vous.",
    "was.cta.trial": "Essai gratuit 14 jours",
    "was.cta.demo": "Réserver une démo",

    // Enterprise Page
    "enterprise.hero.title.prefix": "Taskey",
    "enterprise.hero.title.highlight": "Enterprise",
    "enterprise.hero.subtitle": "Solutions sur mesure et exclusives pour les organisations leaders — disponibles pour des partenaires sélectionnés uniquement",
    "enterprise.hero.admission": "Admission sur candidature et examen uniquement",
    "enterprise.hero.desc1": "Nous proposons un programme Enterprise strictement limité. Les candidatures sont examinées individuellement et seules les entreprises répondant à nos exigences élevées en matière de taille, de normes de sécurité et de pertinence commerciale sont acceptées.",
    "enterprise.hero.desc2": "Les conditions peuvent inclure : taille minimale (100+ employés), leadership de marché démontrable ou importance stratégique et exigences d'intégration avancées.",
    "enterprise.hero.note": "Note : L'admission est soumise à un examen individuel.",
    "enterprise.when.title": "Quand Enterprise est-il fait pour vous ?",
    "enterprise.when.subtitle": "Nous recommandons Enterprise aux entreprises ayant des exigences uniques et une pertinence stratégique",
    "enterprise.cta.apply": "Demander Enterprise",
    "enterprise.cta.demo": "Réserver une démo",

    // Premium Manager Page
    "manager.hero.badge": "SERVICE PREMIUM",
    "manager.hero.title": "Taskey Premium Manager",
    "manager.hero.subtitle": "Votre expert personnel pour votre entreprise",
    "manager.cta.request": "Demander maintenant",
    "manager.cta.demo": "Réserver une démo",
    "manager.price": "239 € / semaine",
  },
};

const LanguageContext = createContext<LanguageContextType>({
  language: "de",
  setLanguage: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("de");

  useEffect(() => {
    const saved = localStorage.getItem("taskey-language") as Language | null;
    if (saved && ["de", "en", "tr", "fr"].includes(saved)) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("taskey-language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] ?? translations["de"][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
